"""
B-3 extraction script: parses the canonical vault doc "Phil OS - How You
Operate Variant Content" and generates lib/how-you-operate-registry.js.

Registry shape per the vault doc's own stated design: per variant id,
{ variantId, strength: { pattern, whereItShowsUp, cost, lever },
  failureMode: { pattern, whereItShowsUp, cost, lever } }.

Run: python extract_how_you_operate.py
"""
import re
import json

import os

DOC = os.environ.get(
    "HOW_YOU_OPERATE_DOC",
    r"C:\Andre's 2nd brain\750 - Other Ventures\757 - Phil OS\Build Log and Decisions\Phil OS - How You Operate Variant Content.md",
)
OUT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "lib", "how-you-operate-registry.js"))

text = open(DOC, encoding="utf-8").read()
body = text.split("\n## Open questions", 1)[0]

# Variant headers appear at either ### (Family 1) or #### (Families 2-12)
# depth: "### 1A - The Activist" or "#### 2A - The Systemic Analyst".
variant_pattern = re.compile(r"^#{3,4} (\d{1,2}[A-E]) - .+$", re.M)
matches = list(variant_pattern.finditer(body))
assert len(matches) == 60, f"expected 60 variant headers, found {len(matches)}"

entries = {}
order = []
for i, m in enumerate(matches):
    variant_id = m.group(1)
    order.append(variant_id)
    start = m.end()
    end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
    block = body[start:end]

    def extract_section(label):
        # e.g. "**Strength - Some Title**" followed by 4 bullet lines.
        sec_re = re.compile(
            r"\*\*" + label + r" - (.+?)\*\*\n"
            r"- Pattern: (.+?)\n"
            r"- Where it shows up: (.+?)\n"
            r"- Cost: (.+?)\n"
            r"- Lever: (.+?)(?:\n\n|\n$|$)",
            re.S,
        )
        sm = sec_re.search(block)
        assert sm, f"{variant_id}: {label} section not found or malformed"
        title, pattern, where, cost, lever = [g.strip() for g in sm.groups()]
        return {"title": title, "pattern": pattern, "whereItShowsUp": where, "cost": cost, "lever": lever}

    entries[variant_id] = {
        "variantId": variant_id,
        "strength": extract_section("Strength"),
        "failureMode": extract_section("Failure mode"),
    }

assert len(entries) == 60
assert order == sorted(order, key=lambda v: (int(v[:-1]), v[-1])) or True  # order not asserted strictly here

def js_string(s):
    return json.dumps(s, ensure_ascii=False)

def js_expansion(e):
    return (
        "{ title: %s, pattern: %s, whereItShowsUp: %s, cost: %s, lever: %s }"
        % (js_string(e["title"]), js_string(e["pattern"]), js_string(e["whereItShowsUp"]), js_string(e["cost"]), js_string(e["lever"]))
    )

lines = []
lines.append("// B-1/B-2/B-3 extraction, 2026-08-02: inert How You Operate content registry.")
lines.append("//")
lines.append("// Holds the four-part (pattern / where it shows up / cost / lever) expansion")
lines.append("// of each variant's existing strength/failureMode one-liners (see the canonical")
lines.append("// vault document \"Phil OS - How You Operate Variant Content\", B-3) - the vault")
lines.append("// doc is the review surface and source of truth; this module is the")
lines.append("// machine-readable encoding. Do not hand-edit content strings here: re-parse")
lines.append("// from the vault doc so the two cannot drift (DI-005 principle), the same")
lines.append("// discipline lib/belief-map-registry.js and lib/alignment-library-registry.js")
lines.append("// follow. Generated by scripts/extract-how-you-operate-registry.py.")
lines.append("//")
lines.append("// DELIBERATELY INERT: nothing imports this module yet. Wiring this content")
lines.append("// into any product surface (as expandable detail under the existing How You")
lines.append("// Operate cards, per the vault doc's own open question 3) is its own")
lines.append("// separately authorized block. Andre approved the four-part format and the")
lines.append("// Family 1 exemplar tranche 2026-08-01; Lyra's construct/equal-dignity review")
lines.append("// of all 60 variants CLOSED PASS WITH REQUIRED MICRO-FIXES, then fixed,")
lines.append("// 2026-08-01. Andre voice sign-off across the full 120-expansion set is a")
lines.append("// separate, not-yet-recorded gate - this registry extraction does not imply it.")
lines.append("//")
lines.append("// Same dependency-free CommonJS convention as lib/belief-map-registry.js.")
lines.append("")
lines.append("'use strict';")
lines.append("")
lines.append("const REGISTRY_SCHEMA_VERSION = 1;")
lines.append("")
lines.append("const VARIANT_IDS = Object.freeze([")
for vid in order:
    lines.append(f"  {js_string(vid)},")
lines.append("]);")
lines.append("")
lines.append("const HOW_YOU_OPERATE_REGISTRY = Object.freeze({")
for vid in order:
    e = entries[vid]
    lines.append(f"  {js_string(vid)}: Object.freeze({{")
    lines.append(f"    variantId: {js_string(vid)},")
    lines.append(f"    strength: Object.freeze({js_expansion(e['strength'])}),")
    lines.append(f"    failureMode: Object.freeze({js_expansion(e['failureMode'])}),")
    lines.append("  }),")
lines.append("});")
lines.append("")
lines.append("function getVariantExpansion(variantId) {")
lines.append("  return HOW_YOU_OPERATE_REGISTRY[variantId] || null;")
lines.append("}")
lines.append("")
lines.append("module.exports = {")
lines.append("  REGISTRY_SCHEMA_VERSION,")
lines.append("  VARIANT_IDS,")
lines.append("  HOW_YOU_OPERATE_REGISTRY,")
lines.append("  getVariantExpansion,")
lines.append("};")
lines.append("")

out = "\n".join(lines)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(out)

print(f"Wrote {OUT}: {len(entries)} variants, {len(out)} chars")
