"""
B-2 extraction script: parses the canonical vault doc "Phil OS - Culture
Map Variant Content" and generates lib/culture-map-registry.js.

Registry shape per the vault doc's own stated design: per variant id,
{ variantId, films: [{title, why}], music: [{title, why}], books: [{title, why}] }.

Run: python extract_culture_map.py
"""
import re
import json

import os

DOC = os.environ.get(
    "CULTURE_MAP_DOC",
    r"C:\Andre's 2nd brain\750 - Other Ventures\757 - Phil OS\Build Log and Decisions\Phil OS - Culture Map Variant Content.md",
)
OUT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "lib", "culture-map-registry.js"))

text = open(DOC, encoding="utf-8").read()
body = text.split("\n## Decisions, ruled", 1)[0]

variant_pattern = re.compile(r"^### (\d{1,2}[A-E]) - .+$", re.M)
matches = list(variant_pattern.finditer(body))
assert len(matches) == 60, f"expected 60 variant headers, found {len(matches)}"

CATEGORY_KEY = {"Film": "films", "Music": "music", "Book": "books"}

entries = {}
order = []
for i, m in enumerate(matches):
    variant_id = m.group(1)
    order.append(variant_id)
    start = m.end()
    end = matches[i + 1].start() if i + 1 < len(matches) else len(body)
    block = body[start:end]

    item_re = re.compile(r"^- \*\*(Film|Music|Book) - (.+?):\*\* (.+)$", re.M)
    items = list(item_re.finditer(block))
    assert len(items) == 3, f"{variant_id}: expected 3 category bullets, found {len(items)}"

    entry = {"variantId": variant_id, "films": [], "music": [], "books": []}
    seen_categories = []
    for im in items:
        category, title, why = im.group(1), im.group(2).strip(), im.group(3).strip()
        key = CATEGORY_KEY[category]
        seen_categories.append(category)
        entry[key].append({"title": title, "why": why})
    assert seen_categories == ["Film", "Music", "Book"], f"{variant_id}: unexpected category order {seen_categories}"
    entries[variant_id] = entry

assert len(entries) == 60

def js_string(s):
    return json.dumps(s, ensure_ascii=False)

def js_item_list(items):
    parts = [
        "{ title: %s, why: %s }" % (js_string(it["title"]), js_string(it["why"]))
        for it in items
    ]
    return "[" + ", ".join(parts) + "]"

lines = []
lines.append("// B-1/B-2/B-3 extraction, 2026-08-02: inert Culture Map content registry.")
lines.append("//")
lines.append("// Holds each variant's film/music/book selections and variant-specific \"why")
lines.append("// this matches you\" text (see the canonical vault document \"Phil OS -")
lines.append("// Culture Map Variant Content\", B-2) - the vault doc is the review surface")
lines.append("// and source of truth; this module is the machine-readable encoding. Do not")
lines.append("// hand-edit content strings here: re-parse from the vault doc so the two")
lines.append("// cannot drift (DI-005 principle), the same discipline lib/belief-map-registry.js")
lines.append("// and lib/alignment-library-registry.js follow. Generated by")
lines.append("// scripts/extract-culture-map-registry.py.")
lines.append("//")
lines.append("// Every title is drawn verbatim from the live MEDIA_BY_FAMILY object")
lines.append("// (index.html) per the vault doc's own content standard; items may repeat")
lines.append("// across sibling variants within a family (Andre/Lyra-ruled 2026-08-01), each")
lines.append("// with a distinct, variant-specific \"why\" angle. No new curation: every title")
lines.append("// here already existed in MEDIA_BY_FAMILY before this registry was built.")
lines.append("//")
lines.append("// DELIBERATELY INERT: nothing imports this module yet. Wiring this content")
lines.append("// into any product surface (replacing MEDIA_BY_FAMILY's family-level note")
lines.append("// field with variant-level why-text) is its own separately authorized block.")
lines.append("// Lyra's construct/equal-dignity review of all 60 variants CLOSED, format")
lines.append("// approved 2026-08-01. Andre voice sign-off across the full 180-assignment")
lines.append("// set is a separate, not-yet-recorded gate - this registry extraction does")
lines.append("// not imply it.")
lines.append("//")
lines.append("// Same dependency-free CommonJS convention as lib/belief-map-registry.js.")
lines.append("")
lines.append("'use strict';")
lines.append("")
lines.append("const REGISTRY_SCHEMA_VERSION = 1;")
lines.append("")
lines.append("const VARIANT_IDS = Object.freeze([")
for vid in order:
    lines.append(f"  {js_string(vid)},")
lines.append("]);")
lines.append("")
lines.append("const CULTURE_MAP_REGISTRY = Object.freeze({")
for vid in order:
    e = entries[vid]
    lines.append(f"  {js_string(vid)}: Object.freeze({{")
    lines.append(f"    variantId: {js_string(vid)},")
    lines.append(f"    films: Object.freeze({js_item_list(e['films'])}),")
    lines.append(f"    music: Object.freeze({js_item_list(e['music'])}),")
    lines.append(f"    books: Object.freeze({js_item_list(e['books'])}),")
    lines.append("  }),")
lines.append("});")
lines.append("")
lines.append("function getVariantCultureMap(variantId) {")
lines.append("  return CULTURE_MAP_REGISTRY[variantId] || null;")
lines.append("}")
lines.append("")
lines.append("module.exports = {")
lines.append("  REGISTRY_SCHEMA_VERSION,")
lines.append("  VARIANT_IDS,")
lines.append("  CULTURE_MAP_REGISTRY,")
lines.append("  getVariantCultureMap,")
lines.append("};")
lines.append("")

out = "\n".join(lines)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(out)

print(f"Wrote {OUT}: {len(entries)} variants, {len(out)} chars")

# Sanity: 60 variants x 3 items = 180 item-assignments total.
total_items = sum(len(e["films"]) + len(e["music"]) + len(e["books"]) for e in entries.values())
assert total_items == 180, total_items
print(f"total item-assignments: {total_items}")
